version: "3.9"

services:
  frigate:
    container_name: frigate
    image: ghcr.io/blakeblackshear/frigate:stable
    restart: unless-stopped
    shm_size: "512m" 
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./config:/config
      - ./storage:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1g
    ports:
      - "8971:8971"
      - "8554:8554"
      - "8555:8555"
    environment:
      - FRIGATE_RTSP_PASSWORD=YOUR_PASSWORD
